name: Build

on:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE'
      - '**/README.md'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') && github.repository_owner == 'RikkaW' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Write key
        if: github.ref == 'refs/heads/master'
        run: |
          echo apiKey='${{ secrets.API_KEY }}' >> local.properties
          echo storePassword=${{ secrets.KEYSTORE_PASSWORD }} >> local.properties
          echo keyAlias=${{ secrets.KEYSTORE_ALIAS }} >> local.properties
          echo keyPassword='${{ secrets.KEYSTORE_ALIAS_PASSWORD }}' >> local.properties
          echo storeFile=../key.jks >> local.properties
          echo ${{ secrets.KEYSTORE }} | base64 --decode > key.jks
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-app-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            gradle-deps
      - name: Cache Gradle Build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-app-${{ github.sha }}
          restore-keys: |
            gradle-builds
      - name: Build with Gradle
        id: buildWithGradle
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          ./gradlew :app:validateSigningDebug
          ./gradlew :app:assemble
          echo "::set-output name=releaseName::`ls app/build/outputs/apk/release/yasnac-v*-release.apk | awk -F '(/|.apk)' '{print $6}'`"
          echo "::set-output name=debugName::`ls app/build/outputs/apk/debug/yasnac-v*-debug.apk | awk -F '(/|.apk)' '{print $6}'`"
      - name: Upload release
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.buildWithGradle.outputs.releaseName }}
          path: "app/build/outputs/apk/release/*.apk"
      - name: Upload debug
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.buildWithGradle.outputs.debugName }}
          path: "app/build/outputs/apk/debug/*.apk"
      - name: Upload mappings
        uses: actions/upload-artifact@v2
        with:
          name: mappings
          path: "app/build/outputs/mapping/release"
